### ISSUE TITLE
setTool("selectMode") bug

### ISSUE THREAD

**Issue by deathleader** [lionix-team/vue-image-markup#11]
Hi, i try several time to resolve this bug but there is no way to fix it;
if i use the demo all works fine, but when i download the demo and try to my self the selection mode on circle or rectangle don't work.
Olso if i create my own project i have the same problem.
How i can do?
Thank you.

**Comment by lilitsimonyan98** [comment]
Hi,
The bug has already fixed.
Please,update package version.
