### ISSUE TITLE
Delete elements on Mobile

### ISSUE THREAD

**Issue by bradley-varol** [lionix-team/vue-image-markup#12]
I'd like to use this package to annotate images on mobile and tablet but noticed that you can't delete shapes, text, etc on mobile. It would be great if there was a context menu on-hold on mobile.

Thoughts?

Thanks a lot for this great package.

**Comment by slbedwell** [comment]
In addition to this, it would be great if there was a way to just delete a certain line / shape on a desktop too as the deletion just clears the whole area. 

Or failing that, perhaps an eraser?

**Comment by bradley-varol** [comment]
> In addition to this, it would be great if there was a way to just delete a certain line / shape on a desktop too as the deletion just clears the whole area.
> 
> Or failing that, perhaps an eraser?

You can select an element and press the delete key but an eraser that deletes elements on collision would be great.

**Comment by lilitsimonyan98** [comment]
Hi,
You can delete shapes from editor using **`eraser`** mode ,using **this.$refs.editor.set('eraser')** method.
Please update the version to latest.
Thanks.
