### ISSUE TITLE
Error with prop editorId

### ISSUE THREAD

**Issue by lbeaudou** [lionix-team/vue-image-markup#13]
I need to use multiple editors in the same component. But i get error when use editorId prop

![Capture](https://user-images.githubusercontent.com/7451849/94613207-8d183c80-02a4-11eb-97e1-448c53b8969a.PNG)

**Comment by lilitsimonyan98** [comment]
Hi,
Please update the version to latest.
Now **editorid** accepts only string value.
Thanks.
