### ISSUE TITLE
CORS errors (Cloudfront)

### ISSUE THREAD

**Issue by MarkCondello** [lionix-team/vue-image-markup#19]
We are experiencing CORS errors when passing image urls through props for the setBackgroundImage() method on the Editor component. Please see the request which causes the error below:

`Access to XMLHttpRequest at 'https://xxx.cloudfront.net/attachments/xxx' from origin 'http://dev.xxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by lilitsimonyan98** [comment]
Hi @MarkCondello 
I think, it's depends on image url, which you are passing.
Please send me url to help you more precisaly.

**Comment by MarkCondello** [comment]
Hi @lilitsimonyan98,
Sorry for the late reply. Our studio has just returned from holidays.
In response to your request; here is the image url we are passing in:
image:"https://xxx.cloudfront.net/attachments/xxx-1280px-putnam-house-floor-plansjpg?Expires=1608688406&Signature=lZR4-u42wjMzh56BtqCcEycHcmXYm1WufsdOLDQZba0-gTvup7jKoHdnZLEJJKSP4tjG-VutuMGCUOoJZxK4rfElsfKRQUP~5t5OIT9QoaxQpji8ncqzRkx6BI9UkaC283kO9QFq0xAGQ8J3wZMy9weg5Eeq~CE2FS6gCKpOFzGxGAQ1PdfOuHwRRqG-Z77NgaHwxgShBPEIoSmLfKuQhzmfpqjzDQa6RM~RU21lYSsUANo~gx6hmaXLbbdI6TrhbsbnS5SlvY1LAgPGjOXgmxHphGLzv1mJevFEh3PMzK3gIVhLzqoVah0sjHVqf9BSCEMxL1H9cREEev3w2wL~ww__&Key-Pair-Id=APKAJOPTAMDRBCLRZNTQ"

**Comment by aloggnet** [comment]
Having the exact same issue with a AWS s3 presigned URL.

`Access to XMLHttpRequest at 'https://my-app-bucket.s3.eu-central-1.amazonaws.com/myFile.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKISDLYIIMHUWDIOXBO4A%2F20220318%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20220318T090816Z&X-Amz-Expires=30&X-Amz-Signature=3d727dcefdsjd8nwe4cf2b15ehas7b101f715cc473acaks960f92c7ea54&X-Amz-SignedHeaders=host' 
from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Did anyone find a way to fix this ?

Cheers,

**Comment by aloggnet** [comment]
Here is a working solution for configuring cross-origin resource sharing (CORS) and allow cross-origin access to an AWS resource (s3 bucket in my case):

https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html

For CORS configuration (JSON) refer to: 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html
