### ISSUE TITLE
Id for each markup

### ISSUE THREAD

**Issue by stefandevo** [lionix-team/vue-image-markup#6]
Hi
Thx for this component.
I would like to use it to define rectangles on an image where I later dynamically can add something on these locations.
So basically I upload an image, then draw some rectangles on it to define where I later on the server will add some text. Therefore I need the coordinates of the rectangles, but more important I need to know which rectangle is for what information.
So each rectangle I add on the canvas should be able to have a unique key (to be set in code).
Would this be possible with the component?

**Comment by lilitsimonyan98** [comment]
Hi,
We have added the new feature.
Now you can pass id to rectangles and get it with the help of **getObjectsById(id)** method.
Please update the version to latest.
