### ISSUE TITLE
text issue in tool

### ISSUE THREAD

**Issue by freak111** [lionix-team/vue-image-markup#8]
fabric.js?7a94:25472 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at klass.getFontCache 
![Capture](https://user-images.githubusercontent.com/19659879/88015345-99627980-cb3e-11ea-9233-c152a11ba4b4.PNG)

**Comment by giuseppemariniello** [comment]
same happening to me

**Comment by freak111** [comment]
I resolved it like that 

setTool(type, params) {
      this.currentActiveMethod = type;
      console.log(type, params , this.$refs.editor);
      this.$refs.editor.set(type,  {fontStyle: 'italic' , fontFamily: 'Arial' , fontSize : '22' , fontWeight : '12' });
      if(type == 'text'){
        // this.$refs.editor.addText('addText');
      }
    },

**Comment by lilitsimonyan98** [comment]
The issue have been resolved.
