### ISSUE TITLE
 Identifier as prop

### ISSUE THREAD

**Issue by lsnepomuceno** [lionix-team/vue-image-markup#9]
I would like to suggest that the canvas identifier be passed to Editor.vue as a prop, allowing the use of multiple components on the same screen, as shown in the attached print. See attached examples.
![source-example](https://user-images.githubusercontent.com/14093492/88428575-87493b00-cdcb-11ea-8f2d-edafe115f3de.png)
![browser-canvas-example](https://user-images.githubusercontent.com/14093492/88428578-887a6800-cdcb-11ea-8c70-e359851b0040.png)

**Comment by lilitsimonyan98** [comment]
Thanks for the suggestion.
The feature has already added.
